# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.log_request_listener:
      class: AppBundle\EventListener\LogRequestListener
      arguments: ['@kernel', %endpoint.log_request%]
      tags:
        - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }